keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: starfleet
  resource: enterprise-client
  public-client: true
  principal-attribute: preferred_username

server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
